/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-09-02 05:28:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Page3_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1693629632944L));
    _jspx_dependants.put("jar:file:/D:/TestPrograms-20230523T103712Z-001/TestPrograms/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/AdvClass9/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcr_005fout_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcr_005fset_0026_005fvar_005fvalue_005fscope_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcr_005fremove_0026_005fvar_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcr_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcr_005fforEach_0026_005fvar_005fend_005fbegin;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcr_005fredirect_0026_005furl_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fcr_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fcr_005fset_0026_005fvar_005fvalue_005fscope_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fcr_005fremove_0026_005fvar_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fcr_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fcr_005fforEach_0026_005fvar_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fcr_005fredirect_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fcr_005fout_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fcr_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.release();
    _005fjspx_005ftagPool_005fcr_005fremove_0026_005fvar_005fnobody.release();
    _005fjspx_005ftagPool_005fcr_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fcr_005fforEach_0026_005fvar_005fend_005fbegin.release();
    _005fjspx_005ftagPool_005fcr_005fredirect_0026_005furl_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<h1>\r\n");
      out.write("		");
      if (_jspx_meth_cr_005fout_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	</h1>\r\n");
      out.write("	");
      if (_jspx_meth_cr_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	<h1>");
      if (_jspx_meth_cr_005fout_005f1(_jspx_page_context))
        return;
      out.write("</h1>\r\n");
      out.write("	<p>value after removing</p>\r\n");
      out.write("	");
      if (_jspx_meth_cr_005fremove_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	<h1>");
      if (_jspx_meth_cr_005fout_005f2(_jspx_page_context))
        return;
      out.write("</h1>\r\n");
      out.write("	\r\n");
      out.write("	");
      if (_jspx_meth_cr_005fset_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	Person age:");
      if (_jspx_meth_cr_005fout_005f3(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      out.write('	');
      if (_jspx_meth_cr_005fif_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      out.write('	');
      if (_jspx_meth_cr_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	");
      if (_jspx_meth_cr_005fforEach_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      out.write('	');
      if (_jspx_meth_cr_005fredirect_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_cr_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  cr:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_cr_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fcr_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_cr_005fout_005f0_reused = false;
    try {
      _jspx_th_cr_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_cr_005fout_005f0.setParent(null);
      // /Page3.jsp(14,2) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cr_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'this is jsp jstl'}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_cr_005fout_005f0 = _jspx_th_cr_005fout_005f0.doStartTag();
      if (_jspx_th_cr_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fcr_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_cr_005fout_005f0);
      _jspx_th_cr_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_cr_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_cr_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_cr_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  cr:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_cr_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fcr_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_cr_005fset_005f0_reused = false;
    try {
      _jspx_th_cr_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_cr_005fset_005f0.setParent(null);
      // /Page3.jsp(16,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cr_005fset_005f0.setVar("sname");
      // /Page3.jsp(16,1) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cr_005fset_005f0.setScope("session");
      // /Page3.jsp(16,1) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_cr_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/Page3.jsp(16,1) '${'Suresh'}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${'Suresh'}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_cr_005fset_005f0 = _jspx_th_cr_005fset_005f0.doStartTag();
      if (_jspx_th_cr_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fcr_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.reuse(_jspx_th_cr_005fset_005f0);
      _jspx_th_cr_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_cr_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_cr_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_cr_005fout_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  cr:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_cr_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fcr_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_cr_005fout_005f1_reused = false;
    try {
      _jspx_th_cr_005fout_005f1.setPageContext(_jspx_page_context);
      _jspx_th_cr_005fout_005f1.setParent(null);
      // /Page3.jsp(17,5) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cr_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sname}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_cr_005fout_005f1 = _jspx_th_cr_005fout_005f1.doStartTag();
      if (_jspx_th_cr_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fcr_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_cr_005fout_005f1);
      _jspx_th_cr_005fout_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_cr_005fout_005f1, _jsp_getInstanceManager(), _jspx_th_cr_005fout_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_cr_005fremove_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  cr:remove
    org.apache.taglibs.standard.tag.common.core.RemoveTag _jspx_th_cr_005fremove_005f0 = (org.apache.taglibs.standard.tag.common.core.RemoveTag) _005fjspx_005ftagPool_005fcr_005fremove_0026_005fvar_005fnobody.get(org.apache.taglibs.standard.tag.common.core.RemoveTag.class);
    boolean _jspx_th_cr_005fremove_005f0_reused = false;
    try {
      _jspx_th_cr_005fremove_005f0.setPageContext(_jspx_page_context);
      _jspx_th_cr_005fremove_005f0.setParent(null);
      // /Page3.jsp(19,1) name = var type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cr_005fremove_005f0.setVar("sname");
      int _jspx_eval_cr_005fremove_005f0 = _jspx_th_cr_005fremove_005f0.doStartTag();
      if (_jspx_th_cr_005fremove_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fcr_005fremove_0026_005fvar_005fnobody.reuse(_jspx_th_cr_005fremove_005f0);
      _jspx_th_cr_005fremove_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_cr_005fremove_005f0, _jsp_getInstanceManager(), _jspx_th_cr_005fremove_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_cr_005fout_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  cr:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_cr_005fout_005f2 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fcr_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_cr_005fout_005f2_reused = false;
    try {
      _jspx_th_cr_005fout_005f2.setPageContext(_jspx_page_context);
      _jspx_th_cr_005fout_005f2.setParent(null);
      // /Page3.jsp(20,5) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cr_005fout_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sname}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_cr_005fout_005f2 = _jspx_th_cr_005fout_005f2.doStartTag();
      if (_jspx_th_cr_005fout_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fcr_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_cr_005fout_005f2);
      _jspx_th_cr_005fout_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_cr_005fout_005f2, _jsp_getInstanceManager(), _jspx_th_cr_005fout_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_cr_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  cr:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_cr_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fcr_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_cr_005fset_005f1_reused = false;
    try {
      _jspx_th_cr_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_cr_005fset_005f1.setParent(null);
      // /Page3.jsp(22,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cr_005fset_005f1.setVar("age");
      // /Page3.jsp(22,1) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cr_005fset_005f1.setScope("session");
      // /Page3.jsp(22,1) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_cr_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/Page3.jsp(22,1) '${12 }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${12 }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_cr_005fset_005f1 = _jspx_th_cr_005fset_005f1.doStartTag();
      if (_jspx_th_cr_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fcr_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.reuse(_jspx_th_cr_005fset_005f1);
      _jspx_th_cr_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_cr_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_cr_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_cr_005fout_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  cr:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_cr_005fout_005f3 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fcr_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_cr_005fout_005f3_reused = false;
    try {
      _jspx_th_cr_005fout_005f3.setPageContext(_jspx_page_context);
      _jspx_th_cr_005fout_005f3.setParent(null);
      // /Page3.jsp(23,12) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cr_005fout_005f3.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${age }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_cr_005fout_005f3 = _jspx_th_cr_005fout_005f3.doStartTag();
      if (_jspx_th_cr_005fout_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fcr_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_cr_005fout_005f3);
      _jspx_th_cr_005fout_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_cr_005fout_005f3, _jsp_getInstanceManager(), _jspx_th_cr_005fout_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_cr_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  cr:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_cr_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fcr_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_cr_005fif_005f0_reused = false;
    try {
      _jspx_th_cr_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_cr_005fif_005f0.setParent(null);
      // /Page3.jsp(24,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cr_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${age>=20 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_cr_005fif_005f0 = _jspx_th_cr_005fif_005f0.doStartTag();
      if (_jspx_eval_cr_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("		<h2>Person age is greater than 20</h2>\r\n");
          out.write("	");
          int evalDoAfterBody = _jspx_th_cr_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_cr_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fcr_005fif_0026_005ftest.reuse(_jspx_th_cr_005fif_005f0);
      _jspx_th_cr_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_cr_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_cr_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_cr_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  cr:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_cr_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fcr_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_cr_005fif_005f1_reused = false;
    try {
      _jspx_th_cr_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_cr_005fif_005f1.setParent(null);
      // /Page3.jsp(27,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cr_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${age<20 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_cr_005fif_005f1 = _jspx_th_cr_005fif_005f1.doStartTag();
      if (_jspx_eval_cr_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("		<h2>Person age is less than 20</h2>\r\n");
          out.write("	");
          int evalDoAfterBody = _jspx_th_cr_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_cr_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fcr_005fif_0026_005ftest.reuse(_jspx_th_cr_005fif_005f1);
      _jspx_th_cr_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_cr_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_cr_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_cr_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  cr:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_cr_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fcr_005fforEach_0026_005fvar_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_cr_005fforEach_005f0_reused = false;
    try {
      _jspx_th_cr_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_cr_005fforEach_005f0.setParent(null);
      // /Page3.jsp(31,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cr_005fforEach_005f0.setVar("x");
      // /Page3.jsp(31,1) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cr_005fforEach_005f0.setBegin(1);
      // /Page3.jsp(31,1) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cr_005fforEach_005f0.setEnd(10);
      int[] _jspx_push_body_count_cr_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_cr_005fforEach_005f0 = _jspx_th_cr_005fforEach_005f0.doStartTag();
        if (_jspx_eval_cr_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("		<p>value is: ");
            if (_jspx_meth_cr_005fout_005f4(_jspx_th_cr_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_cr_005fforEach_005f0))
              return true;
            out.write("</p>\r\n");
            out.write("	");
            int evalDoAfterBody = _jspx_th_cr_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_cr_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_cr_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_cr_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_cr_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fcr_005fforEach_0026_005fvar_005fend_005fbegin.reuse(_jspx_th_cr_005fforEach_005f0);
      _jspx_th_cr_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_cr_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_cr_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_cr_005fout_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_cr_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_cr_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  cr:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_cr_005fout_005f4 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fcr_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_cr_005fout_005f4_reused = false;
    try {
      _jspx_th_cr_005fout_005f4.setPageContext(_jspx_page_context);
      _jspx_th_cr_005fout_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_cr_005fforEach_005f0);
      // /Page3.jsp(32,15) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cr_005fout_005f4.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${x }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_cr_005fout_005f4 = _jspx_th_cr_005fout_005f4.doStartTag();
      if (_jspx_th_cr_005fout_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fcr_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_cr_005fout_005f4);
      _jspx_th_cr_005fout_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_cr_005fout_005f4, _jsp_getInstanceManager(), _jspx_th_cr_005fout_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_cr_005fredirect_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  cr:redirect
    org.apache.taglibs.standard.tag.rt.core.RedirectTag _jspx_th_cr_005fredirect_005f0 = (org.apache.taglibs.standard.tag.rt.core.RedirectTag) _005fjspx_005ftagPool_005fcr_005fredirect_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.RedirectTag.class);
    boolean _jspx_th_cr_005fredirect_005f0_reused = false;
    try {
      _jspx_th_cr_005fredirect_005f0.setPageContext(_jspx_page_context);
      _jspx_th_cr_005fredirect_005f0.setParent(null);
      // /Page3.jsp(34,1) name = url type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cr_005fredirect_005f0.setUrl("Page2.jsp");
      int _jspx_eval_cr_005fredirect_005f0 = _jspx_th_cr_005fredirect_005f0.doStartTag();
      if (_jspx_th_cr_005fredirect_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fcr_005fredirect_0026_005furl_005fnobody.reuse(_jspx_th_cr_005fredirect_005f0);
      _jspx_th_cr_005fredirect_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_cr_005fredirect_005f0, _jsp_getInstanceManager(), _jspx_th_cr_005fredirect_005f0_reused);
    }
    return false;
  }
}
